# Generated by Django 2.1.5 on 2019-01-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'note')},
        ),
    ]
